using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Localization = Localization;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class Localization : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Localization(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Localization(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaLocalizationSettings _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaLocalizationSettings MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaLocalizationSettings>(new BGId(5079103115060388602UL,4366862900891059588UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public List<Locale> Locale => BGCodeGenUtils.GetNested<Locale>(_Locale, Index);
	public Locale current
	{
		get => (Locale) _current[Index];
		set => _current[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5601773293864762948UL, 7794904149425353862UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_Locale;
	public static BansheeGz.BGDatabase.BGFieldNested _Locale => _ufle12jhs77_Locale ?? (_ufle12jhs77_Locale = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5035160538340754893UL, 14253729106877244574UL), () => _ufle12jhs77_Locale = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_current;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _current => _ufle12jhs77_current ?? (_ufle12jhs77_current = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5002806739431204148UL, 14820169174600962213UL), () => _ufle12jhs77_current = null));
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private Localization() : base(MetaDefault)
	{
	}
	private Localization(BGId id) : base(MetaDefault, id)
	{
	}
	private Localization(BGMetaEntity meta) : base(meta)
	{
	}
	private Localization(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static Localization FindEntity(Predicate<Localization> filter)
	{
		return (Localization) MetaDefault.FindEntity(entity => filter==null || filter((Localization) entity));
	}
	public static List<Localization> FindEntities(Predicate<Localization> filter, List<Localization> result=null, Comparison<Localization> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Localization> action, Predicate<Localization> filter=null, Comparison<Localization> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((Localization) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((Localization) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((Localization)e1,(Localization)e2));
	}
	public static Localization GetEntity(BGId entityId) => (Localization) MetaDefault.GetEntity(entityId);
	public static Localization GetEntity(int index) => (Localization) MetaDefault[index];
	public static Localization GetEntity(string entityName) => (Localization) MetaDefault.GetEntity(entityName);
	public static Localization NewEntity() => (Localization) MetaDefault.NewEntity();
	public static Localization NewEntity(BGId entityId) => (Localization) MetaDefault.NewEntity(entityId);
	public static Localization NewEntity(Action<Localization> callback)
	{
		return (Localization) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Localization)entity)));
	}
}

public partial class Locale : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Locale(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Locale(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4671154531634431227UL,11773987393087283881UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public Localization Localization
	{
		get => (Localization) _Localization[Index];
		set => _Localization[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5736452755997324129UL, 10682040172290343304UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_Localization;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _Localization => _ufle12jhs77_Localization ?? (_ufle12jhs77_Localization = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5106535801275603578UL, 11994983532959485106UL), () => _ufle12jhs77_Localization = null));
	public List<Alias_rifegrt_Localization> RelatedLocalizationListUsingcurrentRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_Localization>(Alias_rifegrt_Localization._current, Id);
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private Locale() : base(MetaDefault)
	{
	}
	private Locale(BGId id) : base(MetaDefault, id)
	{
	}
	private Locale(BGMetaEntity meta) : base(meta)
	{
	}
	private Locale(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static Locale FindEntity(Predicate<Locale> filter)
	{
		return (Locale) MetaDefault.FindEntity(entity => filter==null || filter((Locale) entity));
	}
	public static List<Locale> FindEntities(Predicate<Locale> filter, List<Locale> result=null, Comparison<Locale> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Locale> action, Predicate<Locale> filter=null, Comparison<Locale> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((Locale) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((Locale) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((Locale)e1,(Locale)e2));
	}
	public static Locale GetEntity(BGId entityId) => (Locale) MetaDefault.GetEntity(entityId);
	public static Locale GetEntity(int index) => (Locale) MetaDefault[index];
	public static Locale GetEntity(string entityName) => (Locale) MetaDefault.GetEntity(entityName);
	public static Locale NewEntity() => (Locale) MetaDefault.NewEntity();
	public static Locale NewEntity(BGId entityId) => (Locale) MetaDefault.NewEntity(entityId);
	public static Locale NewEntity(Action<Locale> callback)
	{
		return (Locale) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Locale)entity)));
	}
	public static Locale NewEntity(Localization owner) => (Locale) MetaDefault.NewEntity(owner);
	public static Locale NewEntity(Localization owner, BGId entityId) => (Locale) MetaDefault.NewEntity(owner, entityId);
	public static Locale NewEntity(Localization owner, Action<Locale> callback)
	{
		return (Locale) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((Locale)entity)));
	}
}

public partial class Yes_No_Master : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Yes_No_Master(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Yes_No_Master(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5760172452568443854UL,5472442676794643613UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String Card
	{
		get => _Card[Index];
		set => _Card[Index] = value;
	}
	public System.Int32 CardNo
	{
		get => _CardNo[Index];
		set => _CardNo[Index] = value;
	}
	public System.Int32 Group
	{
		get => _Group[Index];
		set => _Group[Index] = value;
	}
	public System.String Reversed
	{
		get => _Reversed[Index];
		set => _Reversed[Index] = value;
	}
	public System.Single Yes
	{
		get => _Yes[Index];
		set => _Yes[Index] = value;
	}
	public System.Single No
	{
		get => _No[Index];
		set => _No[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5646372450699711488UL, 14786964187694830758UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Card;
	public static BansheeGz.BGDatabase.BGFieldString _Card => _ufle12jhs77_Card ?? (_ufle12jhs77_Card = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5460223048908295818UL, 1506535186276087952UL), () => _ufle12jhs77_Card = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_CardNo;
	public static BansheeGz.BGDatabase.BGFieldInt _CardNo => _ufle12jhs77_CardNo ?? (_ufle12jhs77_CardNo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5659088793062196160UL, 11415983224057942698UL), () => _ufle12jhs77_CardNo = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Group;
	public static BansheeGz.BGDatabase.BGFieldInt _Group => _ufle12jhs77_Group ?? (_ufle12jhs77_Group = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4888686856213666910UL, 17157831667492852133UL), () => _ufle12jhs77_Group = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Reversed;
	public static BansheeGz.BGDatabase.BGFieldString _Reversed => _ufle12jhs77_Reversed ?? (_ufle12jhs77_Reversed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4955584878018627153UL, 5103723847640222125UL), () => _ufle12jhs77_Reversed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Yes;
	public static BansheeGz.BGDatabase.BGFieldFloat _Yes => _ufle12jhs77_Yes ?? (_ufle12jhs77_Yes = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5540793083828721648UL, 8073100551452570278UL), () => _ufle12jhs77_Yes = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_No;
	public static BansheeGz.BGDatabase.BGFieldFloat _No => _ufle12jhs77_No ?? (_ufle12jhs77_No = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4897380457210088789UL, 13488052593328809150UL), () => _ufle12jhs77_No = null));
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private Yes_No_Master() : base(MetaDefault)
	{
	}
	private Yes_No_Master(BGId id) : base(MetaDefault, id)
	{
	}
	private Yes_No_Master(BGMetaEntity meta) : base(meta)
	{
	}
	private Yes_No_Master(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static Yes_No_Master FindEntity(Predicate<Yes_No_Master> filter)
	{
		return (Yes_No_Master) MetaDefault.FindEntity(entity => filter==null || filter((Yes_No_Master) entity));
	}
	public static List<Yes_No_Master> FindEntities(Predicate<Yes_No_Master> filter, List<Yes_No_Master> result=null, Comparison<Yes_No_Master> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Yes_No_Master> action, Predicate<Yes_No_Master> filter=null, Comparison<Yes_No_Master> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((Yes_No_Master) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((Yes_No_Master) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((Yes_No_Master)e1,(Yes_No_Master)e2));
	}
	public static Yes_No_Master GetEntity(BGId entityId) => (Yes_No_Master) MetaDefault.GetEntity(entityId);
	public static Yes_No_Master GetEntity(int index) => (Yes_No_Master) MetaDefault[index];
	public static Yes_No_Master GetEntity(string entityName) => (Yes_No_Master) MetaDefault.GetEntity(entityName);
	public static Yes_No_Master NewEntity() => (Yes_No_Master) MetaDefault.NewEntity();
	public static Yes_No_Master NewEntity(BGId entityId) => (Yes_No_Master) MetaDefault.NewEntity(entityId);
	public static Yes_No_Master NewEntity(Action<Yes_No_Master> callback)
	{
		return (Yes_No_Master) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Yes_No_Master)entity)));
	}
}

public partial class YES_NO_Evaluation : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new YES_NO_Evaluation(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new YES_NO_Evaluation(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5678345914230048803UL,4631957521748007097UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String Answer
	{
		get => _Answer[Index];
		set => _Answer[Index] = value;
	}
	public System.String GroupName
	{
		get => _GroupName[Index];
		set => _GroupName[Index] = value;
	}
	public System.String Group
	{
		get => _Group[Index];
		set => _Group[Index] = value;
	}
	public System.Int32 GroupNo
	{
		get => _GroupNo[Index];
		set => _GroupNo[Index] = value;
	}
	public System.Int32 GroupIndex
	{
		get => _GroupIndex[Index];
		set => _GroupIndex[Index] = value;
	}
	public System.Single Min
	{
		get => _Min[Index];
		set => _Min[Index] = value;
	}
	public System.Single Max
	{
		get => _Max[Index];
		set => _Max[Index] = value;
	}
	public System.String AnswerRO
	{
		get => _AnswerRO[Index];
		set => _AnswerRO[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5207581044109142833UL, 6102899708159623824UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Answer;
	public static BansheeGz.BGDatabase.BGFieldString _Answer => _ufle12jhs77_Answer ?? (_ufle12jhs77_Answer = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4913076594760812268UL, 13419282038586692243UL), () => _ufle12jhs77_Answer = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_GroupName;
	public static BansheeGz.BGDatabase.BGFieldString _GroupName => _ufle12jhs77_GroupName ?? (_ufle12jhs77_GroupName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5434052202164759138UL, 2651227276502074765UL), () => _ufle12jhs77_GroupName = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Group;
	public static BansheeGz.BGDatabase.BGFieldString _Group => _ufle12jhs77_Group ?? (_ufle12jhs77_Group = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4955463858695654634UL, 3348267092519133880UL), () => _ufle12jhs77_Group = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_GroupNo;
	public static BansheeGz.BGDatabase.BGFieldInt _GroupNo => _ufle12jhs77_GroupNo ?? (_ufle12jhs77_GroupNo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4818111432234944698UL, 14477202569428001942UL), () => _ufle12jhs77_GroupNo = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_GroupIndex;
	public static BansheeGz.BGDatabase.BGFieldInt _GroupIndex => _ufle12jhs77_GroupIndex ?? (_ufle12jhs77_GroupIndex = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5635106619173155596UL, 907041871026087818UL), () => _ufle12jhs77_GroupIndex = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Min;
	public static BansheeGz.BGDatabase.BGFieldFloat _Min => _ufle12jhs77_Min ?? (_ufle12jhs77_Min = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5448687406201196025UL, 988313163076226463UL), () => _ufle12jhs77_Min = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Max;
	public static BansheeGz.BGDatabase.BGFieldFloat _Max => _ufle12jhs77_Max ?? (_ufle12jhs77_Max = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5540676471043842446UL, 8667547905203700896UL), () => _ufle12jhs77_Max = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_AnswerRO;
	public static BansheeGz.BGDatabase.BGFieldString _AnswerRO => _ufle12jhs77_AnswerRO ?? (_ufle12jhs77_AnswerRO = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4814729191175556861UL, 3862701682160620465UL), () => _ufle12jhs77_AnswerRO = null));
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private YES_NO_Evaluation() : base(MetaDefault)
	{
	}
	private YES_NO_Evaluation(BGId id) : base(MetaDefault, id)
	{
	}
	private YES_NO_Evaluation(BGMetaEntity meta) : base(meta)
	{
	}
	private YES_NO_Evaluation(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static YES_NO_Evaluation FindEntity(Predicate<YES_NO_Evaluation> filter)
	{
		return (YES_NO_Evaluation) MetaDefault.FindEntity(entity => filter==null || filter((YES_NO_Evaluation) entity));
	}
	public static List<YES_NO_Evaluation> FindEntities(Predicate<YES_NO_Evaluation> filter, List<YES_NO_Evaluation> result=null, Comparison<YES_NO_Evaluation> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<YES_NO_Evaluation> action, Predicate<YES_NO_Evaluation> filter=null, Comparison<YES_NO_Evaluation> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((YES_NO_Evaluation) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((YES_NO_Evaluation) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((YES_NO_Evaluation)e1,(YES_NO_Evaluation)e2));
	}
	public static YES_NO_Evaluation GetEntity(BGId entityId) => (YES_NO_Evaluation) MetaDefault.GetEntity(entityId);
	public static YES_NO_Evaluation GetEntity(int index) => (YES_NO_Evaluation) MetaDefault[index];
	public static YES_NO_Evaluation GetEntity(string entityName) => (YES_NO_Evaluation) MetaDefault.GetEntity(entityName);
	public static YES_NO_Evaluation NewEntity() => (YES_NO_Evaluation) MetaDefault.NewEntity();
	public static YES_NO_Evaluation NewEntity(BGId entityId) => (YES_NO_Evaluation) MetaDefault.NewEntity(entityId);
	public static YES_NO_Evaluation NewEntity(Action<YES_NO_Evaluation> callback)
	{
		return (YES_NO_Evaluation) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((YES_NO_Evaluation)entity)));
	}
}

public partial class TarotDecks : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new TarotDecks(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new TarotDecks(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4942501018330503789UL,14109744699579586468UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String Card
	{
		get => _Card[Index];
		set => _Card[Index] = value;
	}
	public UnityEngine.GameObject Deck1 => _Deck1[Index];
	public System.Int32 No
	{
		get => _No[Index];
		set => _No[Index] = value;
	}
	public UnityEngine.GameObject Deck2 => _Deck2[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4654203724637973899UL, 12138143412840551604UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Card;
	public static BansheeGz.BGDatabase.BGFieldString _Card => _ufle12jhs77_Card ?? (_ufle12jhs77_Card = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5262290340373921548UL, 251607155517545639UL), () => _ufle12jhs77_Card = null));
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_Deck1;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab _Deck1 => _ufle12jhs77_Deck1 ?? (_ufle12jhs77_Deck1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(5474640615959774634UL, 3743476270496729232UL), () => _ufle12jhs77_Deck1 = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_No;
	public static BansheeGz.BGDatabase.BGFieldInt _No => _ufle12jhs77_No ?? (_ufle12jhs77_No = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5435173672476705401UL, 10228782580807646366UL), () => _ufle12jhs77_No = null));
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_Deck2;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab _Deck2 => _ufle12jhs77_Deck2 ?? (_ufle12jhs77_Deck2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(5727559241943958944UL, 6681843255012287382UL), () => _ufle12jhs77_Deck2 = null));
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private TarotDecks() : base(MetaDefault)
	{
	}
	private TarotDecks(BGId id) : base(MetaDefault, id)
	{
	}
	private TarotDecks(BGMetaEntity meta) : base(meta)
	{
	}
	private TarotDecks(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static TarotDecks FindEntity(Predicate<TarotDecks> filter)
	{
		return (TarotDecks) MetaDefault.FindEntity(entity => filter==null || filter((TarotDecks) entity));
	}
	public static List<TarotDecks> FindEntities(Predicate<TarotDecks> filter, List<TarotDecks> result=null, Comparison<TarotDecks> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<TarotDecks> action, Predicate<TarotDecks> filter=null, Comparison<TarotDecks> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((TarotDecks) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((TarotDecks) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((TarotDecks)e1,(TarotDecks)e2));
	}
	public static TarotDecks GetEntity(BGId entityId) => (TarotDecks) MetaDefault.GetEntity(entityId);
	public static TarotDecks GetEntity(int index) => (TarotDecks) MetaDefault[index];
	public static TarotDecks GetEntity(string entityName) => (TarotDecks) MetaDefault.GetEntity(entityName);
	public static TarotDecks NewEntity() => (TarotDecks) MetaDefault.NewEntity();
	public static TarotDecks NewEntity(BGId entityId) => (TarotDecks) MetaDefault.NewEntity(entityId);
	public static TarotDecks NewEntity(Action<TarotDecks> callback)
	{
		return (TarotDecks) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((TarotDecks)entity)));
	}
}

public partial class TarotTypeFlows : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new TarotTypeFlows(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new TarotTypeFlows(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5006528007605504919UL,9788669992611985562UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Int32 Step
	{
		get => _Step[Index];
		set => _Step[Index] = value;
	}
	public System.String Type
	{
		get => _Type[Index];
		set => _Type[Index] = value;
	}
	public System.String Labels
	{
		get => _Labels[Index];
		set => _Labels[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4995909024407851596UL, 7010349146394101674UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Step;
	public static BansheeGz.BGDatabase.BGFieldInt _Step => _ufle12jhs77_Step ?? (_ufle12jhs77_Step = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5001042146552343419UL, 6284446973477922994UL), () => _ufle12jhs77_Step = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Type;
	public static BansheeGz.BGDatabase.BGFieldString _Type => _ufle12jhs77_Type ?? (_ufle12jhs77_Type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4824451923561144568UL, 17009802408845437578UL), () => _ufle12jhs77_Type = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Labels;
	public static BansheeGz.BGDatabase.BGFieldString _Labels => _ufle12jhs77_Labels ?? (_ufle12jhs77_Labels = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5543838482176103829UL, 14448355596288455311UL), () => _ufle12jhs77_Labels = null));
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private TarotTypeFlows() : base(MetaDefault)
	{
	}
	private TarotTypeFlows(BGId id) : base(MetaDefault, id)
	{
	}
	private TarotTypeFlows(BGMetaEntity meta) : base(meta)
	{
	}
	private TarotTypeFlows(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static TarotTypeFlows FindEntity(Predicate<TarotTypeFlows> filter)
	{
		return (TarotTypeFlows) MetaDefault.FindEntity(entity => filter==null || filter((TarotTypeFlows) entity));
	}
	public static List<TarotTypeFlows> FindEntities(Predicate<TarotTypeFlows> filter, List<TarotTypeFlows> result=null, Comparison<TarotTypeFlows> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<TarotTypeFlows> action, Predicate<TarotTypeFlows> filter=null, Comparison<TarotTypeFlows> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((TarotTypeFlows) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((TarotTypeFlows) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((TarotTypeFlows)e1,(TarotTypeFlows)e2));
	}
	public static TarotTypeFlows GetEntity(BGId entityId) => (TarotTypeFlows) MetaDefault.GetEntity(entityId);
	public static TarotTypeFlows GetEntity(int index) => (TarotTypeFlows) MetaDefault[index];
	public static TarotTypeFlows GetEntity(string entityName) => (TarotTypeFlows) MetaDefault.GetEntity(entityName);
	public static TarotTypeFlows NewEntity() => (TarotTypeFlows) MetaDefault.NewEntity();
	public static TarotTypeFlows NewEntity(BGId entityId) => (TarotTypeFlows) MetaDefault.NewEntity(entityId);
	public static TarotTypeFlows NewEntity(Action<TarotTypeFlows> callback)
	{
		return (TarotTypeFlows) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((TarotTypeFlows)entity)));
	}
}

public partial class ZodiacRoster : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new ZodiacRoster(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new ZodiacRoster(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5147067808229039784UL,10421122762563687867UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String Sign
	{
		get => _Sign[Index];
		set => _Sign[Index] = value;
	}
	public System.String Aka_English
	{
		get => _Aka_English[Index];
		set => _Aka_English[Index] = value;
	}
	public System.String Sign_RO
	{
		get => _Sign_RO[Index];
		set => _Sign_RO[Index] = value;
	}
	public System.String Dates_String_A
	{
		get => _Dates_String_A[Index];
		set => _Dates_String_A[Index] = value;
	}
	public System.Int32 Position
	{
		get => _Position[Index];
		set => _Position[Index] = value;
	}
	public UnityEngine.Sprite ZRound => _ZRound[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4849080844715743559UL, 5685830126565744565UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Sign;
	public static BansheeGz.BGDatabase.BGFieldString _Sign => _ufle12jhs77_Sign ?? (_ufle12jhs77_Sign = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5339685349260402045UL, 16536786771506965657UL), () => _ufle12jhs77_Sign = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Aka_English;
	public static BansheeGz.BGDatabase.BGFieldString _Aka_English => _ufle12jhs77_Aka_English ?? (_ufle12jhs77_Aka_English = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5214100446557474108UL, 4253383342634868411UL), () => _ufle12jhs77_Aka_English = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Sign_RO;
	public static BansheeGz.BGDatabase.BGFieldString _Sign_RO => _ufle12jhs77_Sign_RO ?? (_ufle12jhs77_Sign_RO = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4841667933567816560UL, 11843313492159231393UL), () => _ufle12jhs77_Sign_RO = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Dates_String_A;
	public static BansheeGz.BGDatabase.BGFieldString _Dates_String_A => _ufle12jhs77_Dates_String_A ?? (_ufle12jhs77_Dates_String_A = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4626239652555989183UL, 15929957039093081231UL), () => _ufle12jhs77_Dates_String_A = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Position;
	public static BansheeGz.BGDatabase.BGFieldInt _Position => _ufle12jhs77_Position ?? (_ufle12jhs77_Position = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4812814548109614624UL, 8308272517211056557UL), () => _ufle12jhs77_Position = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_ZRound;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _ZRound => _ufle12jhs77_ZRound ?? (_ufle12jhs77_ZRound = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(4825505713753073775UL, 2244139204542498183UL), () => _ufle12jhs77_ZRound = null));
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private ZodiacRoster() : base(MetaDefault)
	{
	}
	private ZodiacRoster(BGId id) : base(MetaDefault, id)
	{
	}
	private ZodiacRoster(BGMetaEntity meta) : base(meta)
	{
	}
	private ZodiacRoster(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static ZodiacRoster FindEntity(Predicate<ZodiacRoster> filter)
	{
		return (ZodiacRoster) MetaDefault.FindEntity(entity => filter==null || filter((ZodiacRoster) entity));
	}
	public static List<ZodiacRoster> FindEntities(Predicate<ZodiacRoster> filter, List<ZodiacRoster> result=null, Comparison<ZodiacRoster> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<ZodiacRoster> action, Predicate<ZodiacRoster> filter=null, Comparison<ZodiacRoster> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((ZodiacRoster) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((ZodiacRoster) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((ZodiacRoster)e1,(ZodiacRoster)e2));
	}
	public static ZodiacRoster GetEntity(BGId entityId) => (ZodiacRoster) MetaDefault.GetEntity(entityId);
	public static ZodiacRoster GetEntity(int index) => (ZodiacRoster) MetaDefault[index];
	public static ZodiacRoster GetEntity(string entityName) => (ZodiacRoster) MetaDefault.GetEntity(entityName);
	public static ZodiacRoster NewEntity() => (ZodiacRoster) MetaDefault.NewEntity();
	public static ZodiacRoster NewEntity(BGId entityId) => (ZodiacRoster) MetaDefault.NewEntity(entityId);
	public static ZodiacRoster NewEntity(Action<ZodiacRoster> callback)
	{
		return (ZodiacRoster) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((ZodiacRoster)entity)));
	}
}

public partial class ZodiacLabelsContent : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new ZodiacLabelsContent(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new ZodiacLabelsContent(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5169456957114114924UL,2958358474780110762UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String Part
	{
		get => _Part[Index];
		set => _Part[Index] = value;
	}
	public System.String LabelType
	{
		get => _LabelType[Index];
		set => _LabelType[Index] = value;
	}
	public System.Int32 Order
	{
		get => _Order[Index];
		set => _Order[Index] = value;
	}
	public System.String PRE_Label
	{
		get => _PRE_Label[Index];
		set => _PRE_Label[Index] = value;
	}
	public System.String AFTER_Label
	{
		get => _AFTER_Label[Index];
		set => _AFTER_Label[Index] = value;
	}
	public System.String Lang
	{
		get => _Lang[Index];
		set => _Lang[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5105242995803793258UL, 13896140556466553004UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Part;
	public static BansheeGz.BGDatabase.BGFieldString _Part => _ufle12jhs77_Part ?? (_ufle12jhs77_Part = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5450186861392940636UL, 12630422445134834822UL), () => _ufle12jhs77_Part = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_LabelType;
	public static BansheeGz.BGDatabase.BGFieldString _LabelType => _ufle12jhs77_LabelType ?? (_ufle12jhs77_LabelType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4832241787868654002UL, 3551801150251356311UL), () => _ufle12jhs77_LabelType = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Order;
	public static BansheeGz.BGDatabase.BGFieldInt _Order => _ufle12jhs77_Order ?? (_ufle12jhs77_Order = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5696365080461413915UL, 15779780244251980174UL), () => _ufle12jhs77_Order = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_PRE_Label;
	public static BansheeGz.BGDatabase.BGFieldString _PRE_Label => _ufle12jhs77_PRE_Label ?? (_ufle12jhs77_PRE_Label = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4978921239023644029UL, 13699062029638403974UL), () => _ufle12jhs77_PRE_Label = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_AFTER_Label;
	public static BansheeGz.BGDatabase.BGFieldString _AFTER_Label => _ufle12jhs77_AFTER_Label ?? (_ufle12jhs77_AFTER_Label = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4642448405744743537UL, 14679984690082410902UL), () => _ufle12jhs77_AFTER_Label = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Lang;
	public static BansheeGz.BGDatabase.BGFieldString _Lang => _ufle12jhs77_Lang ?? (_ufle12jhs77_Lang = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5344846711899899154UL, 15288491515530922921UL), () => _ufle12jhs77_Lang = null));
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private ZodiacLabelsContent() : base(MetaDefault)
	{
	}
	private ZodiacLabelsContent(BGId id) : base(MetaDefault, id)
	{
	}
	private ZodiacLabelsContent(BGMetaEntity meta) : base(meta)
	{
	}
	private ZodiacLabelsContent(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static ZodiacLabelsContent FindEntity(Predicate<ZodiacLabelsContent> filter)
	{
		return (ZodiacLabelsContent) MetaDefault.FindEntity(entity => filter==null || filter((ZodiacLabelsContent) entity));
	}
	public static List<ZodiacLabelsContent> FindEntities(Predicate<ZodiacLabelsContent> filter, List<ZodiacLabelsContent> result=null, Comparison<ZodiacLabelsContent> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<ZodiacLabelsContent> action, Predicate<ZodiacLabelsContent> filter=null, Comparison<ZodiacLabelsContent> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((ZodiacLabelsContent) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((ZodiacLabelsContent) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((ZodiacLabelsContent)e1,(ZodiacLabelsContent)e2));
	}
	public static ZodiacLabelsContent GetEntity(BGId entityId) => (ZodiacLabelsContent) MetaDefault.GetEntity(entityId);
	public static ZodiacLabelsContent GetEntity(int index) => (ZodiacLabelsContent) MetaDefault[index];
	public static ZodiacLabelsContent GetEntity(string entityName) => (ZodiacLabelsContent) MetaDefault.GetEntity(entityName);
	public static ZodiacLabelsContent NewEntity() => (ZodiacLabelsContent) MetaDefault.NewEntity();
	public static ZodiacLabelsContent NewEntity(BGId entityId) => (ZodiacLabelsContent) MetaDefault.NewEntity(entityId);
	public static ZodiacLabelsContent NewEntity(Action<ZodiacLabelsContent> callback)
	{
		return (ZodiacLabelsContent) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((ZodiacLabelsContent)entity)));
	}
}

public partial class ZodiacMiniRoster : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new ZodiacMiniRoster(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new ZodiacMiniRoster(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4905563135571822906UL,15705800709155814830UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Int32 Position
	{
		get => _Position[Index];
		set => _Position[Index] = value;
	}
	public System.String Preposition
	{
		get => _Preposition[Index];
		set => _Preposition[Index] = value;
	}
	public System.String Sign
	{
		get => _Sign[Index];
		set => _Sign[Index] = value;
	}
	public System.String Lang
	{
		get => _Lang[Index];
		set => _Lang[Index] = value;
	}
	public System.String HoroscopeTitle
	{
		get => _HoroscopeTitle[Index];
		set => _HoroscopeTitle[Index] = value;
	}
	public System.String HoroscopeDateAid1
	{
		get => _HoroscopeDateAid1[Index];
		set => _HoroscopeDateAid1[Index] = value;
	}
	public System.String HoroscopeDateAid2
	{
		get => _HoroscopeDateAid2[Index];
		set => _HoroscopeDateAid2[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5518569707483194595UL, 10983528280487294100UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Position;
	public static BansheeGz.BGDatabase.BGFieldInt _Position => _ufle12jhs77_Position ?? (_ufle12jhs77_Position = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5391898163278217163UL, 6899847500822994339UL), () => _ufle12jhs77_Position = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Preposition;
	public static BansheeGz.BGDatabase.BGFieldString _Preposition => _ufle12jhs77_Preposition ?? (_ufle12jhs77_Preposition = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5059205049949793055UL, 18290127892591216801UL), () => _ufle12jhs77_Preposition = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Sign;
	public static BansheeGz.BGDatabase.BGFieldString _Sign => _ufle12jhs77_Sign ?? (_ufle12jhs77_Sign = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4674484454286720946UL, 10975166614306492065UL), () => _ufle12jhs77_Sign = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Lang;
	public static BansheeGz.BGDatabase.BGFieldString _Lang => _ufle12jhs77_Lang ?? (_ufle12jhs77_Lang = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5539515901917433610UL, 1625492394981580192UL), () => _ufle12jhs77_Lang = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_HoroscopeTitle;
	public static BansheeGz.BGDatabase.BGFieldString _HoroscopeTitle => _ufle12jhs77_HoroscopeTitle ?? (_ufle12jhs77_HoroscopeTitle = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5456705895424332768UL, 11199815392539109540UL), () => _ufle12jhs77_HoroscopeTitle = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_HoroscopeDateAid1;
	public static BansheeGz.BGDatabase.BGFieldString _HoroscopeDateAid1 => _ufle12jhs77_HoroscopeDateAid1 ?? (_ufle12jhs77_HoroscopeDateAid1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5655893170963670612UL, 6475351535921056438UL), () => _ufle12jhs77_HoroscopeDateAid1 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_HoroscopeDateAid2;
	public static BansheeGz.BGDatabase.BGFieldString _HoroscopeDateAid2 => _ufle12jhs77_HoroscopeDateAid2 ?? (_ufle12jhs77_HoroscopeDateAid2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5224518339602993869UL, 6809370775792664739UL), () => _ufle12jhs77_HoroscopeDateAid2 = null));
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private ZodiacMiniRoster() : base(MetaDefault)
	{
	}
	private ZodiacMiniRoster(BGId id) : base(MetaDefault, id)
	{
	}
	private ZodiacMiniRoster(BGMetaEntity meta) : base(meta)
	{
	}
	private ZodiacMiniRoster(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static ZodiacMiniRoster FindEntity(Predicate<ZodiacMiniRoster> filter)
	{
		return (ZodiacMiniRoster) MetaDefault.FindEntity(entity => filter==null || filter((ZodiacMiniRoster) entity));
	}
	public static List<ZodiacMiniRoster> FindEntities(Predicate<ZodiacMiniRoster> filter, List<ZodiacMiniRoster> result=null, Comparison<ZodiacMiniRoster> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<ZodiacMiniRoster> action, Predicate<ZodiacMiniRoster> filter=null, Comparison<ZodiacMiniRoster> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((ZodiacMiniRoster) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((ZodiacMiniRoster) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((ZodiacMiniRoster)e1,(ZodiacMiniRoster)e2));
	}
	public static ZodiacMiniRoster GetEntity(BGId entityId) => (ZodiacMiniRoster) MetaDefault.GetEntity(entityId);
	public static ZodiacMiniRoster GetEntity(int index) => (ZodiacMiniRoster) MetaDefault[index];
	public static ZodiacMiniRoster GetEntity(string entityName) => (ZodiacMiniRoster) MetaDefault.GetEntity(entityName);
	public static ZodiacMiniRoster NewEntity() => (ZodiacMiniRoster) MetaDefault.NewEntity();
	public static ZodiacMiniRoster NewEntity(BGId entityId) => (ZodiacMiniRoster) MetaDefault.NewEntity(entityId);
	public static ZodiacMiniRoster NewEntity(Action<ZodiacMiniRoster> callback)
	{
		return (ZodiacMiniRoster) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((ZodiacMiniRoster)entity)));
	}
}

public partial class Zodiac_to_Tarot : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Zodiac_to_Tarot(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Zodiac_to_Tarot(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5050548447098071612UL,13799984278728603576UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String Card
	{
		get => _Card[Index];
		set => _Card[Index] = value;
	}
	public System.Int32 CardNo
	{
		get => _CardNo[Index];
		set => _CardNo[Index] = value;
	}
	public System.String Type
	{
		get => _Type[Index];
		set => _Type[Index] = value;
	}
	public System.Int32 TypeIndex
	{
		get => _TypeIndex[Index];
		set => _TypeIndex[Index] = value;
	}
	public System.Int32 InterpretationIndex
	{
		get => _InterpretationIndex[Index];
		set => _InterpretationIndex[Index] = value;
	}
	public System.String Interpretation
	{
		get => _Interpretation[Index];
		set => _Interpretation[Index] = value;
	}
	public System.String Lang
	{
		get => _Lang[Index];
		set => _Lang[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4776075059599750358UL, 16097893061518193052UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Card;
	public static BansheeGz.BGDatabase.BGFieldString _Card => _ufle12jhs77_Card ?? (_ufle12jhs77_Card = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5103967706586175018UL, 12003900798198213819UL), () => _ufle12jhs77_Card = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_CardNo;
	public static BansheeGz.BGDatabase.BGFieldInt _CardNo => _ufle12jhs77_CardNo ?? (_ufle12jhs77_CardNo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4889058033788007845UL, 11098988589778624439UL), () => _ufle12jhs77_CardNo = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Type;
	public static BansheeGz.BGDatabase.BGFieldString _Type => _ufle12jhs77_Type ?? (_ufle12jhs77_Type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5583593813117741552UL, 316550625641036961UL), () => _ufle12jhs77_Type = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_TypeIndex;
	public static BansheeGz.BGDatabase.BGFieldInt _TypeIndex => _ufle12jhs77_TypeIndex ?? (_ufle12jhs77_TypeIndex = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5505167508447274818UL, 2132737068430992021UL), () => _ufle12jhs77_TypeIndex = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_InterpretationIndex;
	public static BansheeGz.BGDatabase.BGFieldInt _InterpretationIndex => _ufle12jhs77_InterpretationIndex ?? (_ufle12jhs77_InterpretationIndex = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5075221628088143259UL, 12170362952696092089UL), () => _ufle12jhs77_InterpretationIndex = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Interpretation;
	public static BansheeGz.BGDatabase.BGFieldString _Interpretation => _ufle12jhs77_Interpretation ?? (_ufle12jhs77_Interpretation = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4993777908494917231UL, 6022249372061769350UL), () => _ufle12jhs77_Interpretation = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Lang;
	public static BansheeGz.BGDatabase.BGFieldString _Lang => _ufle12jhs77_Lang ?? (_ufle12jhs77_Lang = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4681840741758329119UL, 12131747878598550197UL), () => _ufle12jhs77_Lang = null));
	private static readonly Localization.Factory _factory0_PFS = new Localization.Factory();
	private static readonly Locale.Factory _factory1_PFS = new Locale.Factory();
	private static readonly Yes_No_Master.Factory _factory2_PFS = new Yes_No_Master.Factory();
	private static readonly YES_NO_Evaluation.Factory _factory3_PFS = new YES_NO_Evaluation.Factory();
	private static readonly TarotDecks.Factory _factory4_PFS = new TarotDecks.Factory();
	private static readonly TarotTypeFlows.Factory _factory5_PFS = new TarotTypeFlows.Factory();
	private static readonly ZodiacRoster.Factory _factory6_PFS = new ZodiacRoster.Factory();
	private static readonly ZodiacLabelsContent.Factory _factory7_PFS = new ZodiacLabelsContent.Factory();
	private static readonly ZodiacMiniRoster.Factory _factory8_PFS = new ZodiacMiniRoster.Factory();
	private static readonly Zodiac_to_Tarot.Factory _factory9_PFS = new Zodiac_to_Tarot.Factory();
	private Zodiac_to_Tarot() : base(MetaDefault)
	{
	}
	private Zodiac_to_Tarot(BGId id) : base(MetaDefault, id)
	{
	}
	private Zodiac_to_Tarot(BGMetaEntity meta) : base(meta)
	{
	}
	private Zodiac_to_Tarot(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static Zodiac_to_Tarot FindEntity(Predicate<Zodiac_to_Tarot> filter)
	{
		return (Zodiac_to_Tarot) MetaDefault.FindEntity(entity => filter==null || filter((Zodiac_to_Tarot) entity));
	}
	public static List<Zodiac_to_Tarot> FindEntities(Predicate<Zodiac_to_Tarot> filter, List<Zodiac_to_Tarot> result=null, Comparison<Zodiac_to_Tarot> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Zodiac_to_Tarot> action, Predicate<Zodiac_to_Tarot> filter=null, Comparison<Zodiac_to_Tarot> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((Zodiac_to_Tarot) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((Zodiac_to_Tarot) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((Zodiac_to_Tarot)e1,(Zodiac_to_Tarot)e2));
	}
	public static Zodiac_to_Tarot GetEntity(BGId entityId) => (Zodiac_to_Tarot) MetaDefault.GetEntity(entityId);
	public static Zodiac_to_Tarot GetEntity(int index) => (Zodiac_to_Tarot) MetaDefault[index];
	public static Zodiac_to_Tarot GetEntity(string entityName) => (Zodiac_to_Tarot) MetaDefault.GetEntity(entityName);
	public static Zodiac_to_Tarot NewEntity() => (Zodiac_to_Tarot) MetaDefault.NewEntity();
	public static Zodiac_to_Tarot NewEntity(BGId entityId) => (Zodiac_to_Tarot) MetaDefault.NewEntity(entityId);
	public static Zodiac_to_Tarot NewEntity(Action<Zodiac_to_Tarot> callback)
	{
		return (Zodiac_to_Tarot) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Zodiac_to_Tarot)entity)));
	}
}
#pragma warning restore 414
