/*
* =================================
*  TIGERFORGE UniREST Client v.3.5
* ---------------------------------
*     Configuration settings
* =================================
*/

namespace TigerForge
{
    public class UniRESTClientConfig
    {
        public static string Key1 = "e6RBDnzEhkP8Ta7WgJNL4Fpd0saGzsMN";
        public static string Key2 = "cnw299K3Fd7OYil1";
        public static string AppID = "99K3";
        public static string ServerUrl = "https://zalmoxeland.ro/UNIREST/";
    }
    public static class API
    {
        public static string userNames_v1 = "userNames/v1/";
        public static string appFeedback_v1 = "appFeedback/v1/";
        public static string notifications_notifications_table = "notifications/notifications_table/";
        public static string notifications_notifications_log = "notifications/notifications_log/";
        public static string thetarotapp_horoscopedaily1card = "thetarotapp/horoscopedaily1card/";
        public static string thetarotapp_notificationsContent = "thetarotapp/notificationsContent/";
        public static string thetarotapp_notificationsController = "thetarotapp/notificationsController/";
        public static string thetarotapp_notificationsAnalytics = "thetarotapp/notificationsAnalytics/";
        public static string thetarotapp_gdpr = "thetarotapp/gdpr/";
        public static string thetarotapp_appVersion = "thetarotapp/appVersion/";
        public static string thetarotapp_masterAdsController = "thetarotapp/masterAdsController/";
        public static string thetarotapp_analyticsButtons = "thetarotapp/analyticsButtons/";
        public static string thetarotapp_analyticsDevice = "thetarotapp/analyticsDevice/";
    }
    [System.Serializable]
    public static class DB
    {
        [System.Serializable]
        public class AppFeedback
        {
            public int id = 0;
            public int user_id = 0;
            public string userGen = "";
            public int score = 0;
            public string suggestion = "";
            public string device_type = "";
            public string device_model = "";
            public string device_os = "";
            public string device_memory = "";
            public string system_language = "";
            public string support_location = "";
            public string support_accelometer = "";
            public string support_gyro = "";
            public string device_UUID = "";
            public string app_version = "";
            public string date = "";
        }

        [System.Serializable]
        public class Notifications
        {
            public int id = 0;
            public int No = 0;
            public string Platform = "";
            public string Subject = "";
            public string Content = "";
        }

        [System.Serializable]
        public class NotificationsLog
        {
            public int id = 0;
            public string userGen = "";
            public int NotificationNo = 0;
        }

        [System.Serializable]
        public class UserNames
        {
            public int id = 0;
            public int user_id = 0;
            public string autogenerated_Name = "";
            public string user_Name = "";
        }

        [System.Serializable]
        public class Tta_AnalyticsButtons
        {
            public int id = 0;
            public string username = "";
            public string buttonTag = "";
            public int clicks = 0;
            public int dateInt = 0;
        }

        [System.Serializable]
        public class Tta_AnalyticsDevice
        {
            public int id = 0;
            public string username = "";
            public string deviceType = "";
            public string deviceModel = "";
            public string deviceOS = "";
            public string systemLanguage = "";
            public string appVersion = "";
            public string date = "";
        }

        [System.Serializable]
        public class Tta_MasterAdsController
        {
            public int id = 0;
            public string Date = "";
            public string NoAdsFlag = "";
        }

        [System.Serializable]
        public class Tta_appVersion
        {
            public int id = 0;
            public string appVersion = "";
        }

        [System.Serializable]
        public class Tta_gdpr
        {
            public int id = 0;
            public string username = "";
            public string acceptanceDate = "";
            public string documentVersion = "";
        }

        [System.Serializable]
        public class Tta_horoscopeDaily_1card
        {
            public int id = 0;
            public string username = "";
            public string unityDate = "";
            public int signNo = 0;
            public int cardNo = 0;
            public int intGeneral = 0;
            public int intPersonal = 0;
            public int intLove = 0;
            public int intCareer = 0;
            public int intFinance = 0;
            public int intSpirit = 0;
        }

        [System.Serializable]
        public class Tta_notifications_analytics
        {
            public int id = 0;
            public string username = "";
            public string analyticsChannel = "";
            public string date = "";
            public string time = "";
            public string deviceModel = "";
            public string deviceOS = "";
            public string appVersion = "";
        }

        [System.Serializable]
        public class Tta_notifications_content
        {
            public int id = 0;
            public string notification_id = "";
            public int notificationIndex = 0;
            public string notificationTitle = "";
            public string notificationContent = "";
            public string iconSmall = "";
            public string iconLarge = "";
            public int delayHours = 0;
        }

        [System.Serializable]
        public class Tta_notifications_controller
        {
            public int id = 0;
            public string username = "";
            public string notification_id = "";
            public string date = "";
        }

        [System.Serializable]
        public class Users
        {
            public int id = 0;
            public string username = "";
            public string password = "";
            public string tokenl = "";
            public string tokenr = "";
            public string tokenw = "";
            public string regdate = "";
            public string logdate = "";
        }

    }
}
