
////* =================================
////* TIGERFORGE UniREST Client v.3.5
////* ---------------------------------
////* Configuration settings
////* =================================
////*/

/////*
////* =================================
////* PASTE HERE YOUR
////* UniREST CLIENT CONFIG
////* ---------------------------------
////* Replace the whole content of
////* this file with the Source Code
////* generated by your UniREST Server
////* application.
////* =================================
////*/

namespace TigerForge
{
    public class UniRESTClientConfig
    {
        public static string Key1 = "";
        public static string Key2 = "";
        public static string AppID = "";
        public static string ServerUrl = "";
    }
}
